[terminal.shell]
program = "/usr/bin/fish"

[font]
size = 12

[font.normal]
family = "Fira Code"
style = "Medium"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
